name: FL-getPro

on:
  push:
    branches: main
  gollum:
  workflow_dispatch:
  schedule:
    - cron: '01 16 * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build and publish
      env:
        USERS: ${{ secrets.USERS }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TYPE: ${{ secrets.TYPE }}
        SEND: ${{ secrets.SEND }}
      run: |
        python main.py
